/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author xp
 */
public class VentanaAhorcado extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAhorcado
     */
    public VentanaAhorcado() {
        initComponents();
        //DIBUJA la imagen del ahorcado si fallos
        dibujaImagen(0);
    }
    
    private void dibujaImagen (int numeroFallos){
        
        ImageIcon miImagen = null;
        
      miImagen = new ImageIcon ((getClass().getResource("/imagenesAhorcado/ahorcado_0.png")));
              
      panelAhorcado.setIcon(miImagen);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BotonA = new javax.swing.JButton();
        BotonI = new javax.swing.JButton();
        BotonH = new javax.swing.JButton();
        BotonG = new javax.swing.JButton();
        BotonF = new javax.swing.JButton();
        BotonE = new javax.swing.JButton();
        BotonD = new javax.swing.JButton();
        BotonC = new javax.swing.JButton();
        BotonB = new javax.swing.JButton();
        BotonÑ = new javax.swing.JButton();
        BotonN = new javax.swing.JButton();
        BotonM = new javax.swing.JButton();
        BotonL = new javax.swing.JButton();
        BotonK = new javax.swing.JButton();
        BotonJ = new javax.swing.JButton();
        BotonQ = new javax.swing.JButton();
        BotonP = new javax.swing.JButton();
        BotonO = new javax.swing.JButton();
        BotonW = new javax.swing.JButton();
        BotonV = new javax.swing.JButton();
        BotonU = new javax.swing.JButton();
        BotonT = new javax.swing.JButton();
        BotonS = new javax.swing.JButton();
        BotonR = new javax.swing.JButton();
        BotonZ = new javax.swing.JButton();
        BotonY = new javax.swing.JButton();
        BotonX = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        panelAhorcado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(506, 506));
        setPreferredSize(new java.awt.Dimension(506, 506));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("_ _ _ _ _");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 470, 63));

        BotonA.setText("A");
        BotonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAActionPerformed(evt);
            }
        });
        getContentPane().add(BotonA, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 317, 42, 42));

        BotonI.setText("I");
        BotonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIActionPerformed(evt);
            }
        });
        getContentPane().add(BotonI, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 42, 42));

        BotonH.setText("H");
        getContentPane().add(BotonH, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 42, 42));

        BotonG.setText("G");
        getContentPane().add(BotonG, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 42, 42));

        BotonF.setText("F");
        BotonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFActionPerformed(evt);
            }
        });
        getContentPane().add(BotonF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 42, 42));

        BotonE.setText("E");
        getContentPane().add(BotonE, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 42, 42));

        BotonD.setText("D");
        getContentPane().add(BotonD, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 317, 42, 42));

        BotonC.setText("C");
        getContentPane().add(BotonC, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 317, 42, 42));

        BotonB.setText("B");
        BotonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBActionPerformed(evt);
            }
        });
        getContentPane().add(BotonB, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 317, 42, 42));

        BotonÑ.setText("Ñ");
        getContentPane().add(BotonÑ, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 368, 42, 42));

        BotonN.setText("N");
        getContentPane().add(BotonN, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 42, 42));

        BotonM.setText("M");
        getContentPane().add(BotonM, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 42, 42));

        BotonL.setText("L");
        getContentPane().add(BotonL, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 42, 42));

        BotonK.setText("K");
        BotonK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonKActionPerformed(evt);
            }
        });
        getContentPane().add(BotonK, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 368, 42, 42));

        BotonJ.setText("J");
        getContentPane().add(BotonJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 368, 42, 42));

        BotonQ.setText("Q");
        BotonQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonQActionPerformed(evt);
            }
        });
        getContentPane().add(BotonQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 42, 42));

        BotonP.setText("P");
        getContentPane().add(BotonP, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 368, 42, 42));

        BotonO.setText("O");
        getContentPane().add(BotonO, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 368, 42, 42));

        BotonW.setText("W");
        getContentPane().add(BotonW, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 419, 42, 42));

        BotonV.setText("V");
        getContentPane().add(BotonV, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 419, 42, 42));

        BotonU.setText("U");
        getContentPane().add(BotonU, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 419, 42, 42));

        BotonT.setText("T");
        getContentPane().add(BotonT, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 419, 42, 42));

        BotonS.setText("S");
        getContentPane().add(BotonS, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 419, 42, 42));

        BotonR.setText("R");
        getContentPane().add(BotonR, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 419, 42, 42));

        BotonZ.setText("Z");
        getContentPane().add(BotonZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 419, 42, 42));

        BotonY.setText("Y");
        getContentPane().add(BotonY, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 419, 42, 42));

        BotonX.setText("X");
        getContentPane().add(BotonX, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 419, 42, 42));

        jButton28.setText(" ");
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 464, 260, 42));
        getContentPane().add(panelAhorcado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 200, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAActionPerformed

    private void BotonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonFActionPerformed

    private void BotonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonBActionPerformed

    private void BotonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonIActionPerformed

    private void BotonKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonKActionPerformed

    private void BotonQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonQActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAhorcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonA;
    private javax.swing.JButton BotonB;
    private javax.swing.JButton BotonC;
    private javax.swing.JButton BotonD;
    private javax.swing.JButton BotonE;
    private javax.swing.JButton BotonF;
    private javax.swing.JButton BotonG;
    private javax.swing.JButton BotonH;
    private javax.swing.JButton BotonI;
    private javax.swing.JButton BotonJ;
    private javax.swing.JButton BotonK;
    private javax.swing.JButton BotonL;
    private javax.swing.JButton BotonM;
    private javax.swing.JButton BotonN;
    private javax.swing.JButton BotonO;
    private javax.swing.JButton BotonP;
    private javax.swing.JButton BotonQ;
    private javax.swing.JButton BotonR;
    private javax.swing.JButton BotonS;
    private javax.swing.JButton BotonT;
    private javax.swing.JButton BotonU;
    private javax.swing.JButton BotonV;
    private javax.swing.JButton BotonW;
    private javax.swing.JButton BotonX;
    private javax.swing.JButton BotonY;
    private javax.swing.JButton BotonZ;
    private javax.swing.JButton BotonÑ;
    private javax.swing.JButton jButton28;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel panelAhorcado;
    // End of variables declaration//GEN-END:variables
}
